- name: systemd socket file
  template:
    src: "graphite-web.socket.j2"
    dest: "/etc/systemd/system/graphite-web.socket"
    owner: "root"
    mode: "0644"
  register: socket_file
  tags:
    - graphite
    - graphite-config

- name: systemd service file
  template:
    src: "graphite-web.service.j2"
    dest: "/etc/systemd/system/graphite-web.service"
    owner: "root"
    mode: 0644
  register: service_file
  tags:
    - graphite
    - graphite-config

- name: reload systemd
  systemd:
    name: "graphite-web"
    daemon_reload: "yes"
  when: socket_file.changed or service_file.changed
  tags:
    - graphite
    - graphite-config

- name: enable graphite-web.socket
  systemd:
    name: "graphite-web.socket"
    enabled: "yes"
    masked: "no"
  when: socket_file.changed
  tags:
    - graphite
    - graphite-config

- name: enable graphite-web.service
  systemd:
    name: "graphite-web.service"
    enabled: "yes"
    masked: "no"
  when: service_file.changed
  tags:
    - graphite
    - graphite-config
